package net.thejadeproject.ascension.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.thejadeproject.ascension.AscensionCraft;
import net.thejadeproject.ascension.common.blocks.ModBlocks;
import net.thejadeproject.ascension.util.ModTags;

import javax.annotation.Nullable;
import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {
    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, AscensionCraft.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {


        tag(ModTags.Blocks.NEEDS_SPIRITUAL_STONE_TOOL)
                .addTag(BlockTags.NEEDS_DIAMOND_TOOL);
        tag(ModTags.Blocks.INCORRECT_FOR_SPIRITUAL_STONE_TOOL)
                .addTag(BlockTags.INCORRECT_FOR_IRON_TOOL)
                .remove(ModTags.Blocks.NEEDS_SPIRITUAL_STONE_TOOL);

        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                //FormationsArrays





                .add(ModBlocks.JADE_BLOCK.get())
                .add(ModBlocks.JADE_ORE.get())
                .add(ModBlocks.BLACK_IRON_ORE.get())
                .add(ModBlocks.BLACK_IRON_BLOCK.get())
                .add(ModBlocks.FROST_SILVER_ORE.get())
                .add(ModBlocks.FROST_SILVER_BLOCK.get())
                .add(ModBlocks.SPIRITUAL_STONE_CLUSTER.get())
                .add(ModBlocks.SPIRITUAL_STONE_BLOCK.get())

                .add(ModBlocks.RAW_MARBLE.get())
                .add(ModBlocks.POLISHED_MARBLE.get())
                .add(ModBlocks.MARBLE_BRICKS.get())
                .add(ModBlocks.MARBLE_CHISELED.get())
                .add(ModBlocks.MARBLE_TILES.get())
                .add(ModBlocks.MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.MARBLE_TILE_SLABS.get())
                .add(ModBlocks.MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.MARBLE_TILE_WALLS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE.get())
                .add(ModBlocks.POLISHED_LIGHT_GRAY_MARBLE.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICKS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_CHISELED.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILES.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.GRAY_MARBLE.get())
                .add(ModBlocks.GRAY_POLISHED_MARBLE.get())
                .add(ModBlocks.GRAY_MARBLE_BRICKS.get())
                .add(ModBlocks.GRAY_MARBLE_CHISELED.get())
                .add(ModBlocks.GRAY_MARBLE_TILES.get())
                .add(ModBlocks.GRAY_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.GRAY_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.GRAY_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.GRAY_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.GRAY_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.GRAY_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.CHARRED_MARBLE.get())
                .add(ModBlocks.POLISHED_BURNED_MARBLE.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICKS.get())
                .add(ModBlocks.CHARRED_MARBLE_CHISELED.get())
                .add(ModBlocks.CHARRED_MARBLE_TILES.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.CHARRED_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.CHARRED_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.CHARRED_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.BROWN_MARBLE.get())
                .add(ModBlocks.BROWN_POLISHED_MARBLE.get())
                .add(ModBlocks.BROWN_MARBLE_BRICKS.get())
                .add(ModBlocks.BROWN_MARBLE_CHISELED.get())
                .add(ModBlocks.BROWN_MARBLE_TILES.get())
                .add(ModBlocks.BROWN_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.BROWN_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.BROWN_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.BROWN_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.BROWN_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.BROWN_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.RED_MARBLE.get())
                .add(ModBlocks.RED_POLISHED_MARBLE.get())
                .add(ModBlocks.RED_MARBLE_BRICKS.get())
                .add(ModBlocks.RED_MARBLE_CHISELED.get())
                .add(ModBlocks.RED_MARBLE_TILES.get())
                .add(ModBlocks.RED_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.RED_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.RED_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.RED_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.RED_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.RED_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.ORANGE_MARBLE.get())
                .add(ModBlocks.ORANGE_POLISHED_MARBLE.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICKS.get())
                .add(ModBlocks.ORANGE_MARBLE_CHISELED.get())
                .add(ModBlocks.ORANGE_MARBLE_TILES.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.ORANGE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.ORANGE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.ORANGE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.YELLOW_MARBLE.get())
                .add(ModBlocks.YELLOW_POLISHED_MARBLE.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICKS.get())
                .add(ModBlocks.YELLOW_MARBLE_CHISELED.get())
                .add(ModBlocks.YELLOW_MARBLE_TILES.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.YELLOW_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.YELLOW_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.YELLOW_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.LIME_MARBLE.get())
                .add(ModBlocks.LIME_POLISHED_MARBLE.get())
                .add(ModBlocks.LIME_MARBLE_BRICKS.get())
                .add(ModBlocks.LIME_MARBLE_CHISELED.get())
                .add(ModBlocks.LIME_MARBLE_TILES.get())
                .add(ModBlocks.LIME_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.LIME_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.LIME_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.LIME_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.LIME_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.LIME_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.GREEN_MARBLE.get())
                .add(ModBlocks.GREEN_POLISHED_MARBLE.get())
                .add(ModBlocks.GREEN_MARBLE_BRICKS.get())
                .add(ModBlocks.GREEN_MARBLE_CHISELED.get())
                .add(ModBlocks.GREEN_MARBLE_TILES.get())
                .add(ModBlocks.GREEN_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.GREEN_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.GREEN_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.GREEN_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.GREEN_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.GREEN_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.CYAN_MARBLE.get())
                .add(ModBlocks.CYAN_POLISHED_MARBLE.get())
                .add(ModBlocks.CYAN_MARBLE_BRICKS.get())
                .add(ModBlocks.CYAN_MARBLE_CHISELED.get())
                .add(ModBlocks.CYAN_MARBLE_TILES.get())
                .add(ModBlocks.CYAN_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.CYAN_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.CYAN_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.CYAN_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.CYAN_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.CYAN_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE.get())
                .add(ModBlocks.LIGHT_BLUE_POLISHED_MARBLE.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICKS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_CHISELED.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILES.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.BLUE_MARBLE.get())
                .add(ModBlocks.BLUE_POLISHED_MARBLE.get())
                .add(ModBlocks.BLUE_MARBLE_BRICKS.get())
                .add(ModBlocks.BLUE_MARBLE_CHISELED.get())
                .add(ModBlocks.BLUE_MARBLE_TILES.get())
                .add(ModBlocks.BLUE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.BLUE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.BLUE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.BLUE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.BLUE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.BLUE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.PURPLE_MARBLE.get())
                .add(ModBlocks.PURPLE_POLISHED_MARBLE.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICKS.get())
                .add(ModBlocks.PURPLE_MARBLE_CHISELED.get())
                .add(ModBlocks.PURPLE_MARBLE_TILES.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.PURPLE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.PURPLE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.PURPLE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.MAGENTA_MARBLE.get())
                .add(ModBlocks.MAGENTA_POLISHED_MARBLE.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICKS.get())
                .add(ModBlocks.MAGENTA_MARBLE_CHISELED.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILES.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.PINK_MARBLE.get())
                .add(ModBlocks.PINK_POLISHED_MARBLE.get())
                .add(ModBlocks.PINK_MARBLE_BRICKS.get())
                .add(ModBlocks.PINK_MARBLE_CHISELED.get())
                .add(ModBlocks.PINK_MARBLE_TILES.get())
                .add(ModBlocks.PINK_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.PINK_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.PINK_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.PINK_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.PINK_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.PINK_MARBLE_TILE_WALLS.get())




                .add(ModBlocks.CAULDRON_PEDESTAL_BLOCK.get())
                .add(ModBlocks.FLAME_STAND_BLOCK.get())
                .add(ModBlocks.PILL_CAULDRON_HUMAN_LOW.get());


        tag(ModTags.Blocks.DESTRUCTIBLE_BLOCKS)
                .add(Blocks.STONE)
                .add(Blocks.GRANITE)
                .add(Blocks.ANDESITE)
                .add(Blocks.DIORITE)
                .add(Blocks.DEEPSLATE)
                .add(Blocks.GRAVEL)
                .add(Blocks.SAND)
                .add(Blocks.TUFF)
                .add(Blocks.DIRT)
                .add(Blocks.NETHERRACK)
                .add(Blocks.BLACKSTONE)
                .add(Blocks.BASALT)
                .add(ModBlocks.RAW_MARBLE.get());

        tag(ModTags.Blocks.LINKABLE_CONTAINERS)
                .add(Blocks.CHEST)
                .add(Blocks.BARREL);

        tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(ModBlocks.JADE_ORE.get())
                .add(ModBlocks.SPIRITUAL_STONE_CLUSTER.get())
                .add(ModBlocks.JADE_BLOCK.get())
                .add(ModBlocks.PILL_CAULDRON_HUMAN_LOW.get())
                .add(ModBlocks.CAULDRON_PEDESTAL_BLOCK.get())
                .add(ModBlocks.FLAME_STAND_BLOCK.get());

        tag(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.JADE_ORE.get())
                .add(ModBlocks.BLACK_IRON_ORE.get())
                .add(ModBlocks.BLACK_IRON_BLOCK.get())
                .add(ModBlocks.FROST_SILVER_BLOCK.get())
                .add(ModBlocks.FROST_SILVER_ORE.get())
                .add(ModBlocks.TECHNIQUE_STAND.get());

        tag(BlockTags.FENCES)
                .add(ModBlocks.GOLDEN_PALM_FENCE.get())
                .add(ModBlocks.IRONWOOD_FENCE.get());
        tag(BlockTags.FENCE_GATES)
                .add(ModBlocks.GOLDEN_PALM_FENCE_GATE.get())
                .add(ModBlocks.IRONWOOD_FENCE_GATE.get());
        tag(BlockTags.STAIRS)
                .add(ModBlocks.MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.GRAY_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.GRAY_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.CHARRED_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.BROWN_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.BROWN_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.RED_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.RED_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.ORANGE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.YELLOW_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.LIME_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.LIME_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.GREEN_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.GREEN_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.CYAN_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.CYAN_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.BLUE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.BLUE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.PURPLE_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILE_STAIRS.get())
                .add(ModBlocks.PINK_MARBLE_BRICK_STAIRS.get())
                .add(ModBlocks.PINK_MARBLE_TILE_STAIRS.get());

        tag(BlockTags.SLABS)
                .add(ModBlocks.MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.MARBLE_TILE_SLABS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.GRAY_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.GRAY_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.CHARRED_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.BROWN_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.BROWN_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.RED_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.RED_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.ORANGE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.YELLOW_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.LIME_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.LIME_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.GREEN_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.GREEN_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.CYAN_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.CYAN_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.BLUE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.BLUE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.PURPLE_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILE_SLABS.get())
                .add(ModBlocks.PINK_MARBLE_BRICK_SLABS.get())
                .add(ModBlocks.PINK_MARBLE_TILE_SLABS.get());


        tag(BlockTags.WALLS)
                .add(ModBlocks.CHARRED_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.CHARRED_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.MARBLE_TILE_WALLS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.LIGHT_GRAY_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.GRAY_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.GRAY_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.BROWN_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.BROWN_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.RED_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.RED_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.ORANGE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.ORANGE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.YELLOW_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.YELLOW_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.LIME_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.LIME_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.GREEN_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.GREEN_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.CYAN_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.CYAN_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.LIGHT_BLUE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.BLUE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.BLUE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.PURPLE_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.PURPLE_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.MAGENTA_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.MAGENTA_MARBLE_TILE_WALLS.get())
                .add(ModBlocks.PINK_MARBLE_BRICK_WALLS.get())
                .add(ModBlocks.PINK_MARBLE_TILE_WALLS.get());

        this.tag(BlockTags.LOGS_THAT_BURN)
                .add(ModBlocks.GOLDEN_PALM_LOG.get())
                .add(ModBlocks.GOLDEN_PALM_WOOD.get())
                .add(ModBlocks.STRIPPED_GOLDEN_PALM_LOG.get())
                .add(ModBlocks.STRIPPED_GOLDEN_PALM_WOOD.get())
                .add(ModBlocks.IRONWOOD_LOG.get())
                .add(ModBlocks.IRONWOOD_WOOD.get())
                .add(ModBlocks.STRIPPED_IRONWOOD_LOG.get())
                .add(ModBlocks.STRIPPED_IRONWOOD_WOOD.get());

        this.tag(BlockTags.MINEABLE_WITH_AXE)
                        .add(ModBlocks.CUSHION_WHITE.get())
                        .add(ModBlocks.CUSHION_LIGHT_GRAY.get())
                        .add(ModBlocks.CUSHION_GRAY.get())
                        .add(ModBlocks.CUSHION_BLACK.get())
                        .add(ModBlocks.CUSHION_BROWN.get())
                        .add(ModBlocks.CUSHION_RED.get())
                        .add(ModBlocks.CUSHION_ORANGE.get())
                        .add(ModBlocks.CUSHION_YELLOW.get())
                        .add(ModBlocks.CUSHION_LIME.get())
                        .add(ModBlocks.CUSHION_GREEN.get())
                        .add(ModBlocks.CUSHION_CYAN.get())
                        .add(ModBlocks.CUSHION_LIGHT_BLUE.get())
                        .add(ModBlocks.CUSHION_BLUE.get())
                        .add(ModBlocks.CUSHION_PURPLE.get())
                        .add(ModBlocks.CUSHION_MAGENTA.get())
                        .add(ModBlocks.CUSHION_PINK.get())
                        .add(ModBlocks.TECHNIQUE_STAND.get())
                        .add(ModBlocks.GOLDEN_PALM_PLANKS.get())
                        .add(ModBlocks.IRONWOOD_PLANKS.get());


        tag(ModTags.Blocks.STORAGE_BLOCKS_BLACK_IRON)
                .add(ModBlocks.BLACK_IRON_BLOCK.get());

        tag(ModTags.Blocks.STORAGE_BLOCKS_FROST_SILVER)
                .add(ModBlocks.FROST_SILVER_BLOCK.get());

    }
}
